utilities
error: aString
	"Takes a string and throws an exception containing it."
	
	self call: 'error' with: aString